# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, null=True, verbose_name=b'Nom ')),
                ('country', models.CharField(max_length=150, null=True, verbose_name=b'Pays ')),
                ('height', models.IntegerField(null=True, verbose_name=b'Taille ')),
                ('team', models.CharField(max_length=150, null=True, verbose_name=b'\xc3\x89quipe ')),
                ('ic', models.CharField(max_length=10, null=True, verbose_name=b'Ind. Carac. ')),
                ('imc', models.CharField(max_length=10, null=True, verbose_name=b'IMC ')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name=b'Last Update ')),
                ('age', models.IntegerField(null=True, verbose_name=b'Age ')),
                ('defense', models.IntegerField(null=True, verbose_name=b'Defense ')),
                ('freethrow', models.IntegerField(null=True, verbose_name=b'Lancer F. ')),
                ('twopts', models.IntegerField(null=True, verbose_name=b'2pts ')),
                ('threepts', models.IntegerField(null=True, verbose_name=b'3pts ')),
                ('dribbling', models.IntegerField(null=True, verbose_name=b'Dribble ')),
                ('passing', models.IntegerField(null=True, verbose_name=b'Passe ')),
                ('speed', models.IntegerField(null=True, verbose_name=b'Vitesse ')),
                ('footwork', models.IntegerField(null=True, verbose_name=b'Jeu de Jambe ')),
                ('rebond', models.IntegerField(null=True, verbose_name=b'Rebond ')),
                ('experience', models.IntegerField(null=True, verbose_name=b'Experience ')),
            ],
        ),
    ]
