# Generated by Django 2.2 on 2021-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, null=True, verbose_name='Nom ')),
                ('country', models.CharField(max_length=150, null=True, verbose_name='Pays ')),
                ('height', models.IntegerField(null=True, verbose_name='Taille ')),
                ('team', models.CharField(max_length=150, null=True, verbose_name='Équipe ')),
                ('ic', models.CharField(max_length=10, null=True, verbose_name='Ind. Carac. ')),
                ('imc', models.CharField(max_length=10, null=True, verbose_name='IMC ')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='Last Update ')),
                ('age', models.IntegerField(null=True, verbose_name='Age ')),
                ('defense', models.IntegerField(null=True, verbose_name='Defense ')),
                ('freethrow', models.IntegerField(null=True, verbose_name='Lancer F. ')),
                ('twopts', models.IntegerField(null=True, verbose_name='2pts ')),
                ('threepts', models.IntegerField(null=True, verbose_name='3pts ')),
                ('dribbling', models.IntegerField(null=True, verbose_name='Dribble ')),
                ('passing', models.IntegerField(null=True, verbose_name='Passe ')),
                ('speed', models.IntegerField(null=True, verbose_name='Vitesse ')),
                ('footwork', models.IntegerField(null=True, verbose_name='Jeu de Jambe ')),
                ('rebond', models.IntegerField(null=True, verbose_name='Rebond ')),
                ('experience', models.IntegerField(null=True, verbose_name='Experience ')),
            ],
        ),
    ]
