# Generated by Django 2.2 on 2021-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210318_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=10, null=True, verbose_name='Positiion'),
        ),
    ]
